/**
 * AI summaries for indexed documents — fills the IndexedFile.summary field
 * with a 2–3 sentence description generated by the local model. Explicitly
 * user-triggered (Files tab button), never automatic: generation takes time
 * and warms the model, so it shouldn't happen behind the user's back.
 */
import { ollamaClient } from "@/services/api/ollama";
import { stripThinking } from "@/services/thinking";
import { useFileStore } from "@/stores/fileStore";
import { useModelStore } from "@/stores/modelStore";
import { useSettingsStore } from "@/stores/settingsStore";

/** ~2k tokens of document text — plenty for a short summary */
const MAX_INPUT_CHARS = 8000;

/**
 * Summarize an indexed file with the active model and store the result on
 * the file. Returns the summary; throws with a user-facing message when the
 * file has no text or the model call fails.
 */
export async function summarizeFile(fileId: string): Promise<string> {
  const file = useFileStore.getState().files.find((f) => f.id === fileId);
  if (!file?.content?.trim()) {
    throw new Error("This file has no extracted text to summarize.");
  }

  const model = useModelStore.getState().activeModelId;
  const { keepAlive } = useSettingsStore.getState().settings.models;

  const excerpt = file.content.slice(0, MAX_INPUT_CHARS);
  const truncatedNote =
    file.content.length > MAX_INPUT_CHARS ? " (The document continues beyond this excerpt.)" : "";
  const prompt =
    `Summarize the following document in 2-3 plain sentences. ` +
    `State what it is and what it covers. Reply with only the summary — no preamble, no headings.${truncatedNote}\n\n` +
    `Document: ${file.name}\n\n${excerpt}`;

  const raw = await ollamaClient.generate(model, prompt, {
    temperature: 0.3,
    numPredict: 160,
    keepAlive: keepAlive === "always" ? -1 : (keepAlive ?? "10m"),
  });

  // Reasoning models emit <think> blocks even through /api/generate
  const summary = stripThinking(raw).trim();
  if (!summary) throw new Error("The model returned an empty summary — try again.");

  useFileStore.getState().updateFile(fileId, { summary });
  return summary;
}
